### ISSUE TITLE
Reinstate /stats page, restrict it to signed-in admin users

### ISSUE THREAD

**Issue by dsjoerg** [DevProgress/HillaryBNB#1]

**Comment by dsjoerg** [comment]
Used to be here: https://github.com/dsjoerg/BernieBNB/blob/45aca31177807006e347ccb502e17af2f0dfadf0/app/views/pages/stats.html.haml

It was removed in https://github.com/dsjoerg/BernieBNB/commit/22b838a564641275173186e83f0378d0f1f9bb31 and can be reinstated once this issue is resolved.

**Comment by wbronitsky** [comment]
Currently, there is no concept of different user types. To solve this issue, should we add that concept? We could whitelist emails or something along those lines to decide who is an admin user and who isn't.

**Comment by dsjoerg** [comment]
@wbronitsky yes i'd say add a boolean flag to the User model for admin

**Comment by dsjoerg** [comment]
@mattjacobus has a PR in progress for this: https://github.com/DevProgress/HillaryBNB/pull/39

**Comment by dsjoerg** [comment]
Done by @mattjacobus
