### ISSUE TITLE
should site be named HillaryBNB?  something else?

### ISSUE THREAD

**Issue by dsjoerg** [DevProgress/HillaryBNB#10]
if you have other ideas for the site name, add them here and do it soon :)
hillarybnb.com is available and i've reserved it.

**Comment by theship** [comment]
Someone has been calling it bluebnb.

**Comment by dsjoerg** [comment]
that is a neat name.  who is someone?  unfortunately bluebnb.com is taken.

**Comment by theship** [comment]
Can't remember if it was Seeyew or Greg or... Oh well, it's taken anyway.

**Comment by dsjoerg** [comment]
hillarybnb it is
