### ISSUE TITLE
Get all tests working

### ISSUE THREAD

**Issue by dsjoerg** [DevProgress/HillaryBNB#15]
Just wrote to the BernieBNB team:

> Hi Al, do you know what the state of the BernieBNB tests are?
> 
> I got them to run and pass, with only 2 failures out of 99, by leaving out all config information.
> The two that fail are
> 
> rspec ./spec/mailers/registration_mailer_spec.rb:14 # UserMailer Registration Email should send an email with the correct user information
> rspec ./spec/mailers/signup_mailer_spec.rb:17 # UserMailer Signup Email should send an email with the correct user information
> 
> However if I config mailgun and run the tests, then many more tests fail with (WebMock::NetConnectNotAllowedError: Real HTTP connections are disabled.)
> 
> Curious to know what state testing is in for you, and if there are any special config settings you used to get it to work, if it's working.
> 
> Thank you,  —David

**Comment by dsjoerg** [comment]
Al writes:

> All tests pass for me locally when I ran 
> 
> RAILS_ENV=test rake
> 
> with this config file: config/application.yml (I used "..." to specifiy removed characters)
> 
> USERNAME: jasnow
> PASSWORD: unknown
> IP: http://localhost:3000/
> MAILER_URL: http://localhost:3000/
> FACEBOOK_KEY: "..."
> FACEBOOK_SECRET: "..."
> GOOGLE_CLIENT_ID: "....apps.googleusercontent.com"
> GOOGLE_CLIENT_SECRET: "..."
> BING_GEOCODE_ID: ...
> 
> development:
>   MAILGUN_API_KEY:       "..."
>   MAILGUN_DOMAIN:        "sandbox....mailgun.org"
>   MAILGUN_PUBLIC_KEY:    "pubkey-..."
>   MAILGUN_SMTP_LOGIN:    "postmaster@sandbox....mailgun.org"
>   MAILGUN_SMTP_PASSWORD: "..."
>   MAILGUN_SMTP_PORT:     "587"
>   MAILGUN_SMTP_SERVER:   "smtp.mailgun.org"

**Comment by dsjoerg** [comment]
all tests pass hooray

**Comment by mt0321** [comment]
Updated the application.yml.example file such that the tests will all pass by default if that file's content is used as application.yml. https://github.com/DevProgress/HillaryBNB/commit/68faa836836cf6662914ceae823a7b5af4ff10eb
