### ISSUE TITLE
admin@hillarybnb.com forward to a distribution list of maintainers

### ISSUE THREAD

**Issue by dsjoerg** [DevProgress/HillaryBNB#17]
to DJ, MT and MJ's email

**Comment by dsjoerg** [comment]
and update airbrake to email to admin@hillarybnb.com, and update the site email addresses to all send to admin@hillarybnb.com

**Comment by mt0321** [comment]
Remaining work:
1. Noticed the registration email came from info@hillarybnb.com. Should we be using that as the contact email instead? For now updated emails to admin@ -- https://github.com/DevProgress/HillaryBNB/commit/6695ec0f7194e408b3d633728955ab2a5438cf4b
2. Do we need to update the email address emails are being sent from? (If so -- how are the ENV variables (e.g. DEFAULT_SENDER_ADDRESS) set?)
3. Update Airbrake to send emails to admin@ (I don't have access to Airbrake account)

**Comment by dsjoerg** [comment]
1. works for me
2. done, updated
3. done, updated

i believe you do have access to the airbrake account via the heroku account.
