### ISSUE TITLE
add Google Analytics so we can see traffic sources & funnel stats

### ISSUE THREAD

**Issue by dsjoerg** [DevProgress/HillaryBNB#18]
which may give us ideas about how to improve the site, and help us know which promotions of the site are effective.

**Comment by mt0321** [comment]
Basic integration is complete: https://github.com/DevProgress/HillaryBNB/commit/2bd310cb71ad0ae6656cbca2d3ae938f80198fab
(Still needs to be deployed.)

**Comment by dsjoerg** [comment]
Deployed, it is alive!
