### ISSUE TITLE
set up AppCanary or some other kind of continuous security monitoring

### ISSUE THREAD

**Issue by dsjoerg** [DevProgress/HillaryBNB#19]
let's not get hacked or at least not hacked easily

**Comment by mveytsman** [comment]
Hey @dsjoerg,

I'd love to help out in any way I can!

(cofounder of Appcanary here)

**Comment by dsjoerg** [comment]
omg its @mveytsman !!!  <3

thanks hopefully one of the team can get it set up easily, if we run into trouble we'll letcha know

**Comment by dsjoerg** [comment]
OK its done thanks @mveytsman !!
