### ISSUE TITLE
Local development confirmation email uses localhost:3000

### ISSUE THREAD

**Issue by kmiyashiro** [DevProgress/HillaryBNB#29]
The email uses `localhost:3000` as the hostname for the confirmation link.

**Comment by dsjoerg** [comment]
What hostname should it use?

**Comment by kmiyashiro** [comment]
it should probably use `MAILER_URL` from `application.yml`, although I'm not sure what else that is used for. There are various URLs in there that seem suitable:
- `SITE_URL`
- `MAILER_URL`
- `BASE_DOMAIN`

**Comment by dsjoerg** [comment]
I looked at the code for a while and can't figure out where the hostname is coming from.  In app/views/user_mailer/registration_confirmation.html.erb there is `<%= link_to "HillaryBNB - Confirm Your Email", confirm_email_user_url(@user.confirm_token) %>` but I can't find `confirm_email_user_url` in devise or anywhere else.  Probably some Rails magic going on where a URL is automagically being created from a route, but just a guess.

**Comment by mt0321** [comment]
Looks like it is coming from these:

> config/environments/test.rb
> 42:  config.action_mailer.default_url_options = { :host => 'localhost:3000' }
> config/environments/development.rb
> 41:  config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }

**Comment by dsjoerg** [comment]
@kmiyashiro you want to take this one on?
