### ISSUE TITLE
Add continuous integration testing such as CircleCI

### ISSUE THREAD

**Issue by dsjoerg** [DevProgress/HillaryBNB#35]
So that PRs are automatically checked.

**Comment by kmiyashiro** [comment]
Looks like a `.travis.yml` already exists, should just be a matter of changing some of those values and setting up Travis?

**Comment by dsjoerg** [comment]
@kmiyashiro could be!  Could you take this on?

**Comment by kmiyashiro** [comment]
I'll take a look, do we have a circleCI or travis account? or just use my own?

**Comment by dsjoerg** [comment]
We do not have an account.  There are some official DevProgress instructions (here)[https://github.com/DevProgress/onboarding/wiki/Using-Circle-CI-with-Github-Pages-for-Continuous-Delivery] and they say to use your own if I'm reading it right.

**Comment by dsjoerg** [comment]
I asked Brady to give CircleCI access to the DevProgress github so that it can integrate here directly.

**Comment by dsjoerg** [comment]
w00t w00t first green build! https://circleci.com/gh/DevProgress/HillaryBNB/11
