### ISSUE TITLE
AirBNB integration

### ISSUE THREAD

**Issue by dsjoerg** [DevProgress/HillaryBNB#38]
one of the BernieBNB authors [mentioned](https://www.reddit.com/r/CodersForSanders/comments/4pqmyi/seeyouinphillycom/d4o74j5?st=iqejz33j&sh=5f67e174):

> I believe the lack of background checks were bringing some questionable hosts to their platform. If only I had another month until the convention I could have integrated with AirBnB. That's what they should have done from the beginning. That would have taken care of the problem.
> I doubt I'd be able to integrate AirBnB and release before July. This alone was a ton of work.

**Comment by davidgljay** [comment]
It doesn't look like AirBnB has an official API, the unofficial API is listed here:

http://airbnbapi.org/

More research (and possible legal consultation) would be required before moving ahead with implementing this. It looks like this should allow someone to authenticate via google or FB with AirBnB, retrieve their user info, and confirm if they're a verified host. Is that the goal?

**Comment by dsjoerg** [comment]
Great find, David.

Rather than do this, we are in talks with the campaign to allow them to indicate whether or not a host or guest is "vetted".

I'll close this for now.
