### ISSUE TITLE
COPY: VETTING DISCLAIMER more explicit and dire

### ISSUE THREAD

**Issue by dsjoerg** [DevProgress/HillaryBNB#43]
Emails to hosts and guests currently say "We strongly recommend that potential hosts and visitors connect over social media before making any housing plans."

Instead we need to make it clear that:
- guests and hosts have not been vetted by the campaign, by volunteers, or by anyone else
- it is your responsibility to contact potential hosts and visitors in advance and decide whether it is safe for you to stay with them

maybe craigslist or airbnb have language we can steal.

**Comment by dsjoerg** [comment]
Hey @mattjacobus @nankrafft how about:
`
"WARNING: while most users of HillaryBNB are friendly, trustworthy and responsible Hillary supporters, some of them might not be.  We have NOT vetted HillaryBNB users at all.  It is YOUR responsibility to evaluate potential hosts and visitors and decide if it's safe to proceed.
`

**Comment by NanKrafft** [comment]
That copy is for sure more direct and along the lines of what we need. I think it might be good to tone it down a bit - seems fearful. 

Consider... 

 "PLEASE NOTE: Guests and hosts have NOT been vetted by the campaign, by volunteers, or by anyone else. It is your responsibility to contact potential hosts and visitors in advance and decide whether you are comfortable and safe staying with them"

We should also see about having a legal eye on this. There might the standard language we can use.

**Comment by NanKrafft** [comment]
@alittlecynical

**Comment by dsjoerg** [comment]
@NanKrafft your revision looks great to me.  I'll update the language to that for now and await further revisions / suggestions.

**Comment by NanKrafft** [comment]
Doc with Copy

https://docs.google.com/document/d/1cxThVacGKHSMLKl6MX5CpEasXvj613l2f9eOo8MLXJQ/edit?ts=57fbfeff

**Comment by NanKrafft** [comment]
USE: 

"PLEASE NOTE: Guests and hosts have NOT been vetted by the campaign, by volunteers, or by anyone else. It is your responsibility to contact potential hosts and visitors in advance and decide whether you are comfortable and safe staying with them"

**Comment by dsjoerg** [comment]
Perfect, we have  been using that language for a few days so this is Done
