### ISSUE TITLE
COPY: Host Contacted Page, CONFIRMATION

### ISSUE THREAD

**Issue by dsjoerg** [DevProgress/HillaryBNB#46]
After hitting the "SEND MY CONTACT INFO" button, the next page's message says "We will send Shawn your contact info!"

However since the emails are sent nightly, maybe it would be more clear to say "We will send Shawn your contact info later tonight!"  That way users don't expect the contact to be made immediately.

**Comment by dsjoerg** [comment]
Hey @mattjacobus @nankrafft if you think this is a good idea I'll go ahead and change this.

**Comment by NanKrafft** [comment]
I would go ahead and do it. @dsjoerg 

I think we still need to think about what we will be doing RE last minute requests.

**Comment by NanKrafft** [comment]
Just went through it. Think that it is confusing that user sees "contacted" with green box/check mark to the right of host name, then sees above that they "will be" contacted. 

I think that the minor change above is good for right now - will not hurt anything, but that YES this needs some work. I will noodle and play with today.

**Comment by dsjoerg** [comment]
OK @NanKrafft minor change is pushed and deployed.   Assigning to you to consider what else if anything should be done.

**Comment by NanKrafft** [comment]
@dsjoerg My suggestion is that emails to hosts continue to go out nightly, BUT if a traveler user selects a start date that is within 48 hours of the current time/date the email to the host goes out immediately. (this would need to be clearly communicated to hosts). 

We could solve for duplicate emails by strongly encouraging hosts to update their listing and remove it once space is filled. 

Thoughts? Difficulty?

**Comment by dsjoerg** [comment]
@NanKrafft that is smart, I like it.

And since nothing in the current production system's language mentions that the emails are daily, we may not even have to change that much in the current wording.

You want to make a new issue for this change?

**Comment by dsjoerg** [comment]
@NanKrafft made #57 to change mail behavior / frequency.  What else needs to be done for this issue?  Some visual change to indicate whether or not the email has actually been sent yet?

**Comment by NanKrafft** [comment]
![screen shot 2016-10-13 at 9 59 22 am](https://cloud.githubusercontent.com/assets/13854320/19358712/c215c7e8-912b-11e6-9a5c-5d20bc5ebd38.png)

**Comment by NanKrafft** [comment]
@dsjoerg Messages still seem a bit confusing. What do you think of just changing it to "Host contacted" 

I know is not as accurate, but might cause less confusion (especially for last minute folks, which might the the bulk of users)

**Comment by dsjoerg** [comment]
@NanKrafft how about we change both the message and the button to accurately say what's going on.  Either "We will send David your contact info later tonight!" or "We have sent David your contact info!" for the green text on top, and "WILL CONTACT HOST TONIGHT" or "HOST CONTACTED" for the green button.

What I'm trying to avoid is the system saying it has sent a message when it hasn't, which makes people think it's broken.  Smart campaign organizers will test us out to see if our system is a risk worth taking for their campaign, and if it says SENT and it ain't sent, they'll think it's broken.

**Comment by NanKrafft** [comment]
@dsjoerg If it is easy to do and differentiate based on the <48hr plan than I think it is a great idea. 

This update pending issue #63

**Comment by dsjoerg** [comment]
Closed in favor of #75
