### ISSUE TITLE
FEATURE: Add ability to create blackout dates for hostings

### ISSUE THREAD

**Issue by dsjoerg** [DevProgress/HillaryBNB#47]
See https://github.com/SandersForPresident/BernieBNB/issues/135

and then also https://github.com/SandersForPresident/BernieBNB/pull/209 and https://github.com/SandersForPresident/BernieBNB/pull/210

**Comment by NanKrafft** [comment]
@dsjoerg this seems important. where are we at in terms of technical build. Can we get this feature in ASAP? Think we should.

**Comment by dsjoerg** [comment]
I emailed @fpcyan to ask if she'd like to finish up her work in https://github.com/SandersForPresident/BernieBNB/pull/210.

**Comment by dsjoerg** [comment]
@nan matt jacobus is going to work on this tomorrow (Tuesday)

**Comment by fpcyan** [comment]
@dsjoerg @NanKrafft I'll see how far I got on this project after work today, and give an estimate for finishing it.

**Comment by dsjoerg** [comment]
w00t thanks @fpcyan !!

**Comment by fpcyan** [comment]
Actually @NanKrafft, @dsjoerg let's clarify who is working on this on this issue instead of via emails? :p

**Comment by dsjoerg** [comment]
So @mattjacobus is working on this issue today / now.  @fpcyan I understand that you won't be able to work on this until after work today, so why don't you check in then and see if he's made enough progress.

**Comment by NanKrafft** [comment]
@fpcyan are you in DevProgress Slack? Would be great to have you in the project channel and some small group DMs. :)

**Comment by dsjoerg** [comment]
@mattjacobus made a lot of progress on this today.  His work is pushed to https://github.com/mattjacobus/hillarybnb.  What remains is to update the nightly email logic to not send emails when there is no date overlap, and to add suitable tests for that.

**Comment by mattjacobus** [comment]
A list of hostings is shown after a visit is created.  This matching logic needs to be changed to ensure date overlap as well.

**Comment by mattjacobus** [comment]
I fixed the list of hostings shown after a visit is created and pushed the change to my fork.  I don't yet understand how the rake tasks work (lib/tasks/send*.rake).
