### ISSUE TITLE
Can't delete host listing

### ISSUE THREAD

**Issue by mattjacobus** [DevProgress/HillaryBNB#48]
It's either not possible or not apparent how to delete a host listing.

**Comment by dsjoerg** [comment]
When you click on your hosting, do you see something like this?

![image](https://cloud.githubusercontent.com/assets/783273/19221710/7bd667be-8e16-11e6-9279-75e1af7d2852.png)

The idea is to click on the I CAN'T HOST button.

**Comment by mattjacobus** [comment]
Uh, aside from the big red button that I didn't notice below "save".  Sorry.

**Comment by dsjoerg** [comment]
Well maybe you won't be the only one to have this problem?   Maybe you can think of something that would work better?

**Comment by mattjacobus** [comment]
I was actually scanning that page for "Delete", similar to what you would see in the iOS contacts app where you edit a contact and then at the bottom is "Delete contact".  My inclination is to change the text to have it say "Cancel" when you're in the process of creating a new listing and "Delete" when you're looking at an existing listing.

**Comment by dsjoerg** [comment]
On BernieBNB it used to be "DELETE" and they changed it to "I AM BOOKED" for some reason.  I asked them why, maybe they'll remember what the problem was for DELETE. https://github.com/SandersForPresident/BernieBNB/commit/1a03635588ff190588160cec32d5d00833aad07f#commitcomment-19353570

**Comment by dsjoerg** [comment]
Imagine that you've set up a hosting and you have 3 people coming to stay at your place, and now you're full and don't want any more guests.  I wonder if the host was worried to hit DELETE because they were worried that their accepted & wanted guests would be told that they were no longer able to stay at their place.
