### ISSUE TITLE
FEATURE: Text fields for HOST change suggested text 

### ISSUE THREAD

**Issue by NanKrafft** [DevProgress/HillaryBNB#51]
Hosts offering to share hotel room or blocks will need to be able to let people know the dates and price of rooms/beds that they have available etc. 
- # of beds (how many do they sleep)
- Cost of bed or cost per person 
- Preferred payment method (pay me back using... paypal, check, cash...)
- Only comfortable sharing with... women/men/N/A? (Should this be included) - might be implied in user Name (if women wants women they elect female name)

Dates should work in current date choice flow

Home/Hotel share

**Comment by NanKrafft** [comment]
@dsjoerg I suggest that we get rid of the character limit and instead add suggested text in text field. 

Example if hotel share: 
- What is the cost per room per night (for hotel share)?

Example if room/bed in home: 
- twin bed in shared room

Would like this to be an OR - am going to add feature for Host to select if it is a "host in home" or "share hotel or other accommodations" 

![screen shot 2016-10-11 at 11 48 02 am](https://cloud.githubusercontent.com/assets/13854320/19283985/e88ada50-8fa8-11e6-90f1-2bea296ce226.png)

**Comment by dsjoerg** [comment]
OK @NanKrafft do you want to design/write this more or is this ready for a developer to start working on?

**Comment by NanKrafft** [comment]
SEE/PENDING issue 58
https://github.com/DevProgress/HillaryBNB/issues/58

**Comment by dsjoerg** [comment]
Once #58 is done, is this ready for a developer to start working on?

**Comment by dsjoerg** [comment]
OK @NanKrafft, #58 is done, opening this up for a developer who wants to take it

**Comment by dsjoerg** [comment]
@NanKrafft do you want the suggestion text "twin bed in shared room" to be **in** the text field or below it?   We currently have text in the text field **and** below it, can you specify what you'd like done with each?

**Comment by NanKrafft** [comment]
@dsjoerg I was originally thinking it would be in the text field (replacing the current character limit note), but it could also be just updating the text below. 

**1) We should **remove character limit***\* 

**2) We want to facilitate the sharing of any additional hotel info in listing** 

a) Update **question copy**:

Current: "Do you have a message for your visitors?"

Proposed: "Please share any additional information about your accommodations"

b) Update **description copy**:

Current: "e.g. number of available beds or accessible hours."

Proposed: "e.g. number of available beds, cost per person in shared hotel room or rental house, or accessible hours"
