### ISSUE TITLE
ADD Unsubscribe link in our emails - (unsubscribe - delete hosting posted for user)

### ISSUE THREAD

**Issue by dsjoerg** [DevProgress/HillaryBNB#53]
Is it bad that we don't have an unsubscribe link?

I'm thinking about how technically-challenged users might set up a hosting offer or a visit, then receive unwanted emails, and be unclear about how to make them stop.  The last line of our emails say "You can add, edit or delete your host offers anytime here: [HillaryBNB - Host](http://www.hillarybnb.com/hostings/23/edit)".  A savvy user will know to click the link in order to delete their host offer in order to stop getting email.

But a non-savvy user will just want to unsubscribe, won't see an unsubscribe link, and may click the Spam button, and then we start getting Spam-flagged.

**Comment by NanKrafft** [comment]
Could we add a user support email address, or does that open up a can of worms?

**Comment by dsjoerg** [comment]
My 2c would be to do it now at small scale to learn, and then as we ramp up we'll have to take it away.  But it might be a smart thing to do at small scale to accelerate the learning about what the common problems/concerns are.

**Comment by dsjoerg** [comment]
Hey @NanKrafft it turns out that our mail-sending service Mailgun can automatically add an unsubscribe link to the bottom of our emails.

I'd recommend that we do that, so that fewer users classify our emails as spam (which was happening to BernieBNB).  Of course we'd rather that the user click on the link to delete their visit/hostingoffer, but these days when a user wants email to stop, they expect to see an unsubscribe link and don't want to think about it any further than that.

Are you cool with adding the unsubscribe link to emails?

**Comment by NanKrafft** [comment]
@dsjoerg My only concern is that they will unsubscribe, but visitors will think that they are not responding (and keep thinking they are available). It will be a bad user experience on the visitor end. 

Is there any other way to solve for the spam issue? 

It would be added work to have some sort of user support email address, but my guess is that we would really only have a week or so of high volume tickets (if that even happens). I would be happy to man it if we go that route.

**Comment by dsjoerg** [comment]
Good point @NanKrafft.  So how about this:

In the email we have an Unsubscribe link that takes the user to a new Unsubscribe page.

On that page we can confirm that user wants to unsubscribe from all communications and that they are no longer hosting or visiting.  When they click unsubscribe we delete all their active hostings and visits.

**Comment by NanKrafft** [comment]
@dsjoerg YES!

**Comment by dsjoerg** [comment]
closing, work to be done in #72
