### ISSUE TITLE
COPY: Registration Confirmation EMAIL 

### ISSUE THREAD

**Issue by NanKrafft** [DevProgress/HillaryBNB#56]
https://docs.google.com/document/d/1cxThVacGKHSMLKl6MX5CpEasXvj613l2f9eOo8MLXJQ/edit?ts=57fbfeff

**Comment by NanKrafft** [comment]
**Original:** 

Hi Nan ,

Thanks for registering with HillaryBNB! Click the URL below to confirm your registration:

HillaryBNB - Confirm Your Email

Legal Disclaimer: By agreeing to use this service, you hereby agree to waive any and all claims arising from your use of this service against the Hillary Clinton campaign, any groups associated with the Hillary Clinton campaign, and DevProgress.

**Updated:** 

Hey First Name,

You’re nearly there! 

Thanks for registering with Hillary BNB! You just need to click the URL below to confirm your registration. Once you do, you can hop on and start using the site!

[Hillary BNB Email Confirmation Link]

Best of luck!
The Hillary BNB Team

Legal Disclaimer: By agreeing to use this service, you hereby agree to waive any and all claims arising from your use of this service against the operators of HillaryBNB, DevProgress, and Hillary for America

**Comment by dsjoerg** [comment]
Looks good @NanKrafft, you can edit https://github.com/DevProgress/HillaryBNB/blob/master/app/views/user_mailer/registration_confirmation.html.erb to make this change.

**Comment by dsjoerg** [comment]
OK @NanKrafft you did it, and its deployed to production 👍
