### ISSUE TITLE
FEATURE: ADD type of accommodation to HOST LISTING page

### ISSUE THREAD

**Issue by NanKrafft** [DevProgress/HillaryBNB#58]
![screen shot 2016-10-11 at 11 52 43 am](https://cloud.githubusercontent.com/assets/13854320/19284109/63760b0e-8fa9-11e6-8309-642aa5bf7521.png)

Add check box for host to select either...
- Room or bed in my home
  OR
- Share hotel room or other accommodations

Based on selection suggested text in "message to your visitors" will vary

**Comment by NanKrafft** [comment]
@dsjoerg good to go

**Comment by NanKrafft** [comment]
SEE issue 51
https://github.com/DevProgress/HillaryBNB/issues/51

**Comment by dsjoerg** [comment]
OK @NanKrafft this is done and deployed in production.  The suggestion text modification is not yet done, that's issue #51.

**Comment by dsjoerg** [comment]
@NanKrafft I also made it show up in the "user/123" page.  So here it is:

![image](https://cloud.githubusercontent.com/assets/783273/19289069/f0c44304-8fd6-11e6-8421-f9f808e7b95c.png)

![image](https://cloud.githubusercontent.com/assets/783273/19289084/039866ea-8fd7-11e6-94d2-839baab1906b.png)
