### ISSUE TITLE
FEATURE: Room opens up for VISITOR with saved visit EMAIL

### ISSUE THREAD

**Issue by NanKrafft** [DevProgress/HillaryBNB#59]
My suggestion here would be that IF a host becomes available during any of their "saved" visits -> we send a once a day notification that links them back to the page that shows available hosts. Something like "There are now hosts available during one of your visits"

We should also add language that encourages visitors to remove their visits once they have secured accommodations - so they don't get these emails if they no longer need a host.

**Comment by NanKrafft** [comment]
Need COPY for email and to update on request page

![screen shot 2016-10-11 at 3 20 17 pm](https://cloud.githubusercontent.com/assets/13854320/19290844/7a81ab38-8fc6-11e6-8508-2262c52f5b51.png)

**Comment by NanKrafft** [comment]
Copy in this doc 

https://docs.google.com/document/d/1cxThVacGKHSMLKl6MX5CpEasXvj613l2f9eOo8MLXJQ/edit?ts=57fbfeff

**Comment by dsjoerg** [comment]
@NanKrafft I believe what you're asking for in this issue is very similar to the site's current functionality which you may not have known about:

> For each Visit registered in the system, if there are any new Hosting Offers created within the past 24 hours that are within 20 miles of the Visit's zip code, we email them to the visitor. (Note that this means a visitor may receive multiple emails from us if they have multiple pending Visits). (This logic is in https://github.com/DevProgress/HillaryBNB/blob/master/lib/tasks/send_new_hosts_digest.rake)

The text of this email is now in the Google Doc in the final section called "EMAIL - VISITOR - LIST OF NEW POTENTIAL HOSTS"

Have a look and a think & let us know what you'd like to do.

**Comment by NanKrafft** [comment]
![screen shot 2016-10-12 at 10 14 08 am](https://cloud.githubusercontent.com/assets/13854320/19320104/ce033742-9064-11e6-9864-f74541b4e15e.png)

**Comment by NanKrafft** [comment]
@dsjoerg I was just trying to come up with something to solve for multiple emails (if multiple hosts became available within a 24hr period) 

Is this correct?

 If visitor has a request in for a visit to Seattle and 10 new hosts sign up in Seattle within 24 hrs -> User will receive 10 emails each with the individual host?

OR

If visitor has a request in for a visit to Seattle and 10 new hosts sign up in Seattle within 24 hrs -> User will receive 1 daily email with info for all 10 hosts in that area that are now available?

**Comment by dsjoerg** [comment]
The latter, "If visitor has a request in for a visit to Seattle and 10 new hosts sign up in Seattle within 24 hrs -> User will receive 1 daily email with info for all 10 hosts in that area that are now available?"

I tried to explain this in the README:

> For each Visit registered in the system, if there are any new Hosting Offers created within the past 24 hours that are within 20 miles of the Visit's zip code, we email them to the visitor. (Note that this means a visitor may receive multiple emails from us if they have multiple pending Visits).

**Comment by dsjoerg** [comment]
as per discussion with @NanKrafft
