### ISSUE TITLE
Match even if the entire party can't be accommodated

### ISSUE THREAD

**Issue by mattjacobus** [DevProgress/HillaryBNB#62]
I noticed the code in visit.available_hostings only returns a match if the number of travelers is less than or equal to the max number of guests in a host listing.  If you are trying to match a large group, I think it would be useful to see partial matches.

**Comment by dsjoerg** [comment]
good point @mattjacobus i agree that this should be changed.

go for it!

**Comment by NanKrafft** [comment]
+1
