### ISSUE TITLE
FEATURE: send email to HOST immediately if VISIT starts soon

### ISSUE THREAD

**Issue by dsjoerg** [DevProgress/HillaryBNB#63]
(For discussion see #57)
- When a visitor clicks "SEND MY CONTACT INFO", if their visit will begin within 48 hours, the email is sent immediately to the host (an "Instant Email").
- Contacts/Visits for which an Instant Email has been sent are _not_ included in nightly emails to Hosts.

**Comment by nellshamrell** [comment]
Taking a look at this one.

**Comment by nellshamrell** [comment]
Just got my dev environment setup and need to log off for the evening.  Will take a look at this tomorrow evening, but if anyone else wants to pick it up before then please feel free :)

**Comment by dsjoerg** [comment]
@nellshamrell is back on the case!
