### ISSUE TITLE
Don't let user change their email address once their email is verified

### ISSUE THREAD

**Issue by dsjoerg** [DevProgress/HillaryBNB#64]
http://www.hillarybnb.com/users/XXX/edit lets the user change their email address.
However the new email address is not re-verified, which defeats the purpose of email address verification.  People could use HillaryBNB as a spam machine that way.  We don't want to send emails to addresses that didn't verify.

**Comment by explikated** [comment]
Looking into this one...

**Comment by dsjoerg** [comment]
Fixed by @explikated in https://github.com/DevProgress/HillaryBNB/pull/68
