### ISSUE TITLE
improve DNS config; some mailhosts don't like our config

### ISSUE THREAD

**Issue by dsjoerg** [DevProgress/HillaryBNB#69]
Back in August, a mail bounced, and the receiver's mail team looked into it and said:

> Hello,
> 
> Thanks for contacting Gandi.
> 
> The issue here is with the sender address. The logs appear to show the sender address is postmaster@mg.hillarybnb.com. It doesn’t look like this domain name is defined in the DNS zone file for hillarybnb.com. At least when I do a dig on it, I get no response.
> 
> You’ll probably have to check with Mailgun about how to configure this feature correctly. At least, the issue is on the sending side.

**Comment by dsjoerg** [comment]
What's weird about this is that there is a record for mg.hillarybnb.com:

```

was:HillaryBNB david$ dig mg.hillarybnb.com ANY
dig mg.hillarybnb.com ANY

; <<>> DiG 9.8.3-P1 <<>> mg.hillarybnb.com ANY
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42658
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;mg.hillarybnb.com.     IN  ANY

;; ANSWER SECTION:
mg.hillarybnb.com.  1799    IN  TXT "v=spf1 include:mailgun.org ~all"

;; Query time: 98 msec
;; SERVER: 10.0.1.1#53(10.0.1.1)
;; WHEN: Thu Oct 13 09:38:41 2016
;; MSG SIZE  rcvd: 79
```

**Comment by dsjoerg** [comment]
So is the problem that there is no CNAME record for mg.hillarybnb.com?  I can set one up, but I wasn't sure if that would break something else.

**Comment by wingedpig** [comment]
There's no MX record for mg.hillarybnb.com. All you apparently have is an SPF record. Is there a reason you're sending email from the mg subdomain?

**Comment by dsjoerg** [comment]
We discussed on Slack but I'll summarize here for posterity.

Mailgun says

> We recommend using a subdomain with Mailgun, like “mg.mydomain.com”. Using a subdomain you will still be able to send emails from your root domain e.g. “you@mydomain.com”.
> 
> If using a subdomain please make sure that you configure MX records for the subdomain for optimal delivery.

HillaryBNB may be sending hundreds or thousand or emails a day to its users; we would like to use mailgun for sending those emails because I presume that mailgun handles mail ops better than we could handle them ourselves otherwise.   However we would also like there to be admin@hillarybnb.com which can receive messages and goes to a core group of people operating the site.  I had presumed that in order to accomplish that we would need GSuite somehow configured for hillarybnb.com as well.

The setup that we have currently almost works as desired, all messages (except one) have been delivered successfully.

Now that I'm looking at this more closely, I see that mailgun does support forwarding incoming mails (https://documentation.mailgun.com/user_manual.html#routes) so maybe the more robust thing is to use mailgun for everything, set up the domain's MX record as mailgun all the way, and have mailgun forward all foo@hillarybnb.com emails to the operators' personal email addresses.

**Comment by dsjoerg** [comment]
OK!  I think this is fixed.  Will keep this open for a day to confirm.

**Comment by dsjoerg** [comment]
Thanks @wingedpig !

**Comment by dsjoerg** [comment]
Mails have been delivered great.  Previous correspondent who had trouble at Gandi has not been reachable.  Nothing else to be done here until we hear about email problems.
