### ISSUE TITLE
FEATURE: let Instant Emails have different wording

### ISSUE THREAD

**Issue by NanKrafft** [DevProgress/HillaryBNB#71]
PENDING issue #63 completion 

**ADD to Subject of email -** 

**Current:**  "You've been contacted!"

**Proposed:** "You've been contacted! [Urgent]"

**ADD to body of email -** 

**Current:** 
Hi David, 

Thank you for offering to host volunteers on HillaryBNB! **Here are** all the people who have expressed interest in your offer today, October 08, 2016: 

Flynn:

Phone: 415-000-000
Email: test@gmail.com
Dates: 10/08/16 - 10/08/16
Group of 1 

VETTING DISCLAIMER HAS BEEN UPDATED 

You can add, edit or delete your host offers anytime here: HillaryBNB - Host

**Proposed:**

Hi David, 

Thank you for offering to host volunteers on HillaryBNB! **This visitor expressed interest in your offer and hopes to stay with you right away:** 

Flynn:

Phone: 415-000-000
Email: test@gmail.com
Dates: 10/08/16 - 10/08/16
Group of 1 

**Please reach out to this visitor to coordinate their stay as soon as possible.** 

**Thanks!
The HillaryBNB Team**

VETTING DISCLAIMER HAS BEEN UPDATED 

You can add, edit or delete your host offers anytime here: HillaryBNB - Host

**Comment by dsjoerg** [comment]
To be clear, these changes are to be made only to the Instant Emails that are described in #63.  Non-Instant Emails stay as is.
