### ISSUE TITLE
ADD Unsubscribe link to our emails — links to new Unsubscribe page

### ISSUE THREAD

**Issue by dsjoerg** [DevProgress/HillaryBNB#72]
In our emails (except for welcome and registration) we have an Unsubscribe link that takes the user to a new Unsubscribe page.

On that page we can confirm that user wants to unsubscribe from all communications and that they are no longer hosting or visiting. When they click unsubscribe we delete all their active hostings and visits.

(for discussion see #53)

**Comment by dsjoerg** [comment]
to be clear, the idea here is to get rid of the link at the bottom of the emails composed by new_*_digest.html.erb in app/views/user_mailer and replace it with a new Unsubscribe link

**Comment by durka** [comment]
Just new_*_digest.html.erb or all the *.erb in that dir?

**Comment by dsjoerg** [comment]
just new_*_digest.html.erb

**Comment by durka** [comment]
I'm working on it but I might need some Rails help.

**Comment by nellshamrell** [comment]
@durka I am around on chat if you need any help :)

**Comment by durka** [comment]
Should we just delete the whole user account? If not seems like there should be a way to un-unsubscribe. I guess the way you are saying it, they will never get another email because they'll have no active hostings/visits. But if they go and create a new one, or if in the future we take the whole email list and do some kind of "Thanks for participating, on to the next election!" email, they'd get another email, right?

**Comment by dsjoerg** [comment]
Good points.

I'm leaning towards just delete the whole user account (and all associated model records), because it's simple.  If they want to come back, creating an account is super easy.

**Comment by durka** [comment]
OK, well in that case, the Unsubscribe button can just redirect to the `destroy` route, no? So the flow is: clink link in email -> "Are you sure, everything will be deleted" -> click Unsubscribe -> "Successfully deleted account".

**Comment by dsjoerg** [comment]
Yeah, the wording will need adjustment, but we can take care of that after you've implemented it.  I'm not 100% sure how the destroy route works myself but I'll take your word for it :)

**Comment by durka** [comment]
Well, assuming the "Delete account" button from the regular Profile view works, then this will too! :D

**Comment by dsjoerg** [comment]
@durka crushed it, https://github.com/DevProgress/HillaryBNB/pull/80
