### ISSUE TITLE
Make messages and button text reflect true email-sending behavior

### ISSUE THREAD

**Issue by dsjoerg** [DevProgress/HillaryBNB#75]
For reference: ![reference image](https://cloud.githubusercontent.com/assets/13854320/19358712/c215c7e8-912b-11e6-9a5c-5d20bc5ebd38.png)

After #63 is implemented, change both the message and the button to accurately say what's going on.

For Instant Emails say "We have sent David your contact info!" and "HOST CONTACTED" for the green button.

For non-Instant Emails say "We will send David your contact info later tonight!" for the green text on top, and "WILL CONTACT HOST TONIGHT" for the button.  The next day, when the email has been sent, the button should change to "HOST CONTACTED".

See #46 for discussion that led to this.

**Comment by dsjoerg** [comment]
Part of this was done in #78 by @nellshamrell.  What remains is the button which currently says "HOST CONTACTED".

**Comment by explikated** [comment]
Taking a look at this one now...

**Comment by dsjoerg** [comment]
@explikated crushed this with https://github.com/DevProgress/HillaryBNB/pull/90
