### ISSUE TITLE
Show accomodation_type in visits/show and in nightly email to visitors

### ISSUE THREAD

**Issue by dsjoerg** [DevProgress/HillaryBNB#81]
The nightly email to visitors that starts with "Here's a list of all the new hosts available for your visit" lists the available hosts but does not clarify whether they are private homes or hotel shares.

Same goes for the "visits/show" page, the one that a visitor sees when clicking on their own visit that lists available hosts, which starts with "Hosts near <City>; Contact any good matches below".

**Comment by explikated** [comment]
Taking a look at this one now

**Comment by dsjoerg** [comment]
@explikated crushed this in #82
