### ISSUE TITLE
Nasty 500 page shown when browsing to a deleted visit

### ISSUE THREAD

**Issue by dsjoerg** [DevProgress/HillaryBNB#91]
**Airbrake error:** [#9465](https://herokuapp52917062herokucom.airbrake.io/projects/126488/groups/1799632630453469465)
**Airbrake project:** hillarybnb

**Error type:** `ActiveRecord::RecordNotFound`
**Error message:** `Couldn't find Visit with 'id'=58 [WHERE ("visits"."deleted_at" IS NULL)]`
**Where:** `visits#show`
**Occurred at:** Oct 19, 2016 00:28:44 UTC
**First seen at:** Oct 19, 2016 00:28:44 UTC
**Occurrences:** 0 (0 since last deploy on `<no information>`)

**URL:** [http://www.hillarybnb.com/visits/58=4](http://www.hillarybnb.com/visits/58=4)
**File:** `[GEM_ROOT]/gems/activerecord-4.2.7.1/lib/active_record/relation/finder_methods.rb`

**Backtrace:**

```
[GEM_ROOT]/gems/activerecord-4.2.7.1/lib/active_record/relation/finder_methods.rb:324:in raise_record_not_found_exception!
[GEM_ROOT]/gems/activerecord-4.2.7.1/lib/active_record/relation/finder_methods.rb:444:in find_one
[GEM_ROOT]/gems/activerecord-4.2.7.1/lib/active_record/relation/finder_methods.rb:423:in find_with_ids
[GEM_ROOT]/gems/activerecord-4.2.7.1/lib/active_record/relation/finder_methods.rb:71:in find
```

**Comment by dsjoerg** [comment]
This happened when someone deleted a visit and then browsed to it (maybe by using the back button?)

This should be fixed so that instead of throwing a nasty 500 message and sending us an email, it shows a friendly "That visit has been deleted" page.  Or redirects to the home page.

**Comment by dsjoerg** [comment]
And the same should be done for hostings.

**Comment by explikated** [comment]
Taking a look now!

**Comment by explikated** [comment]
Whoops didn't spot this.. https://github.com/DevProgress/HillaryBNB/pull/92.

**Comment by dsjoerg** [comment]
@explikated ouch, sorry about that!  I was asleep at the time.

Won't happen again!

**Comment by mattjacobus** [comment]
My fault @explikated.  Apologies.

**Comment by dsjoerg** [comment]
@explikated crushed this in #93
